def mesh_to_vtk_points(mesh):
    ...

def mesh_to_vtk_cells(mesh, order="linearized"):
    ...

def field_to_point_data(fieldfile):
    ...

def semtex_to_unstructured_grid(mesh, fieldfile):
    ...
